### ISSUE TITLE
Modal window stay opened when starting game using the space keyboard

### ISSUE THREAD

**Issue by R0bertoG** [4skinSkywalker/Lite-Dual_N-back#1]
In [https://4skinskywalker.github.io/Lite-Dual_N-back/](https://4skinskywalker.github.io/Lite-Dual_N-back/) when a session have finished you get a transparent screen with the statistics.

In order to play again you can close the window and click on 'play' or you can use the key 'S'. All this work perfectly.

If you have started the game with a click in "play", the focus is now in that button. When the game finish, you can use the space key to start the game again. Unfortunately this doesn't close the statistics screen and the game start playing with the screen opened.

Congratulations for the project, by the way.

**Comment by 4skinSkywalker** [comment]
Thanks for the notification! I'll fix it in the near future

**Comment by 4skinSkywalker** [comment]
Solved by commit d9f2aa1
